name:XAI
channels:
  - conda-forge
  - pytorch
  - bioconda
  - defaults
dependencies:
  # pyton requirements
  - python=3.8.*
  - matplotlib
  - numpy
  - pandas
  - shap
  - scikit-learn
  - pyensembl
  - torchvision
  - scipy
  - pytorch-lightning
  - torchmetrics
  - pip
    - torch~=1.10.2
  # R requirements
  - r-base
  - r-biocmanager
  - bioconductor-biocinstaller
  - r-wgcna
  - r-webgestaltr=0.4.4
  - r-data.table=1.14.2
  - bioconductor-biomart=2.50.0
