name: XAI
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _r-mutex=1.0.1=anacondar_1
  - absl-py=1.0.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py38h497a2fe_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - alsa-lib=1.2.3=h516909a_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - astroid=2.9.3=py38h578d9bd_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_6
  - bioconductor-annotationdbi=1.56.1=r41hdfd78af_0
  - bioconductor-biobase=2.54.0=r41h5c21468_1
  - bioconductor-biocgenerics=0.40.0=r41hdfd78af_0
  - bioconductor-biocinstaller=1.26.1=0
  - bioconductor-biostrings=2.62.0=r41h5c21468_1
  - bioconductor-genomeinfodb=1.30.0=r41hdfd78af_0
  - bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_1
  - bioconductor-go.db=3.14.0=r41hdfd78af_0
  - bioconductor-impute=1.68.0=r41h77f299f_1
  - bioconductor-iranges=2.28.0=r41h5c21468_1
  - bioconductor-keggrest=1.34.0=r41hdfd78af_0
  - bioconductor-preprocesscore=1.56.0=r41h5c21468_1
  - bioconductor-s4vectors=0.32.3=r41h5c21468_0
  - bioconductor-xvector=0.34.0=r41h5c21468_1
  - bioconductor-zlibbioc=1.40.0=r41h5c21468_1
  - biopython=1.79=py38h497a2fe_1
  - blas=2.113=mkl
  - blas-devel=3.9.0=13_linux64_mkl
  - blinker=1.4=py_1
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py38h497a2fe_1003
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cachetools=5.0.0=pyhd8ed1ab_0
  - cairo=1.16.0=ha00ac49_1009
  - certifi=2021.10.8=py38h578d9bd_1
  - cffi=1.15.0=py38h3931269_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.0.4=py38h578d9bd_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.1=py38h3e25421_0
  - cudatoolkit=10.1.243=h036e899_10
  - curl=7.81.0=h2574ce0_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - datacache=1.1.5=py_0
  - dbus=1.13.6=h5008d03_3
  - expat=2.4.6=h27087fc_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.96=ha180cfb_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.29.1=py38h497a2fe_0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.3.0=py38h497a2fe_0
  - fsspec=2022.2.0=pyhd8ed1ab_0
  - future=0.18.2=py38h578d9bd_4
  - gcc_impl_linux-64=9.4.0=h03d3576_13
  - gcc_linux-64=9.4.0=h391b98a_6
  - gettext=0.19.8.1=h73d1719_1008
  - gfortran_impl_linux-64=9.4.0=h0003116_13
  - gfortran_linux-64=9.4.0=hf0ab688_6
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - google-auth=2.6.0=pyh6c4a22f_1
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - graphite2=1.3.13=h58526e2_1001
  - grpcio=1.44.0=py38hdd6454d_0
  - gsl=2.7=he838d99_0
  - gst-plugins-base=1.18.5=hf529b03_3
  - gstreamer=1.18.5=h9f60fe5_3
  - gtfparse=1.2.1=pyh864c0ab_0
  - gxx_impl_linux-64=9.4.0=h03d3576_13
  - gxx_linux-64=9.4.0=h0316aca_6
  - harfbuzz=3.4.0=hb4a5f5f_0
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.1=py38h578d9bd_0
  - isort=5.10.1=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h7f98852_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - kiwisolver=1.3.2=py38h1fd1430_1
  - krb5=1.19.2=hcc1bbae_3
  - lazy-object-proxy=1.7.1=py38h497a2fe_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_mkl
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=13_linux64_mkl
  - libclang=13.0.1=default_hc23dcda_0
  - libcurl=7.81.0=h2574ce0_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=9.4.0=hd854feb_13
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libglib=2.70.2=h174f98d_4
  - libgomp=11.2.0=h1d223b6_12
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=13_linux64_mkl
  - liblapacke=3.9.0=13_linux64_mkl
  - libllvm11=11.1.0=hf817b99_3
  - libllvm13=13.0.1=hf817b99_2
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=14.2=hd57d9b9_0
  - libprotobuf=3.19.4=h780b84a_0
  - libsanitizer=9.4.0=h79bfe98_13
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-devel_linux-64=9.4.0=hd854feb_13
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=13.0.1=hf817b99_0
  - llvmlite=0.38.0=py38h4630a5e_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - make=4.3=hd18ef5c_1
  - markdown=3.3.6=pyhd8ed1ab_0
  - matplotlib=3.5.1=py38h578d9bd_0
  - matplotlib-base=3.5.1=py38hf4fb855_0
  - mccabe=0.6.1=py_1
  - memoized-property=1.0.3=py_0
  - mkl=2022.0.1=h8d4b97c_803
  - mkl-devel=2022.0.1=ha770c72_804
  - mkl-include=2022.0.1=h8d4b97c_803
  - mock=4.0.3=py38h578d9bd_2
  - multidict=6.0.2=py38h497a2fe_0
  - multipledispatch=0.6.0=py38_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.28=ha770c72_0
  - mysql-libs=8.0.28=hfa10184_0
  - ncurses=6.3=h9c3ff4c_0
  - ninja=1.10.2=h4bd325d_1
  - nspr=4.32=h9c3ff4c_1
  - nss=3.74=hb5efdd6_0
  - numba=0.55.1=py38h4bf6c61_0
  - numpy=1.21.5=py38h87f13fb_0
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py38h43a58ef_0
  - pango=1.48.10=h54213e6_2
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=h032f7d1_0
  - pillow=9.0.1=py38h0ee0e06_2
  - pip=22.0.3=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=2.5.1=pyhd8ed1ab_0
  - progressbar33=2.4=py_0
  - protobuf=3.19.4=py38h709712a_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydeprecate=0.3.2=pyhd8ed1ab_0
  - pyensembl=1.9.4=pyh5e36f6f_0
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pylint=2.12.2=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyqt=5.12.3=py38h578d9bd_8
  - pyqt-impl=5.12.3=py38h0ffb2e6_8
  - pyqt5-sip=4.19.18=py38h709712a_8
  - pyqtchart=5.12=py38h7400c14_8
  - pyqtwebengine=5.12.1=py38h7400c14_8
  - pysocks=1.7.1=py38h578d9bd_4
  - python=3.8.12=ha38a3c6_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.8.1=py3.8_cuda10.1_cudnn7.6.3_0
  - pytorch-lightning=1.5.10=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py38h497a2fe_3
  - qt=5.12.9=ha98a1a1_5
  - r-acepack=1.4.1=r41h859d828_1006
  - r-apcluster=1.4.9=r41h03ef668_0
  - r-askpass=1.1=r41hcfec24a_2
  - r-assertthat=0.2.1=r41hc72bb7e_2
  - r-backports=1.4.1=r41hcfec24a_0
  - r-base=4.1.2=hde4fec0_0
  - r-base64enc=0.1_3=r41hcfec24a_1004
  - r-bibtex=0.4.2.3=r41hcfec24a_0
  - r-biocmanager=1.30.16=r41hc72bb7e_0
  - r-bit=4.0.4=r41hcfec24a_0
  - r-bit64=4.0.5=r41hcfec24a_0
  - r-bitops=1.0_7=r41hcfec24a_0
  - r-blob=1.2.2=r41hc72bb7e_0
  - r-brio=1.1.3=r41hcfec24a_0
  - r-cachem=1.0.6=r41hcfec24a_0
  - r-callr=3.7.0=r41hc72bb7e_0
  - r-checkmate=2.0.0=r41hcfec24a_1
  - r-cli=3.2.0=r41h03ef668_0
  - r-clipr=0.8.0=r41hc72bb7e_0
  - r-cluster=2.1.2=r41h859d828_0
  - r-codetools=0.2_18=r41hc72bb7e_0
  - r-colorspace=2.0_3=r41h06615bd_0
  - r-cpp11=0.4.2=r41hc72bb7e_0
  - r-crayon=1.5.0=r41hc72bb7e_0
  - r-curl=4.3.2=r41hcfec24a_0
  - r-data.table=1.14.2=r41hcfec24a_0
  - r-dbi=1.1.2=r41hc72bb7e_0
  - r-deoptimr=1.0_10=r41hc72bb7e_0
  - r-desc=1.4.0=r41hc72bb7e_0
  - r-diffobj=0.3.5=r41hcfec24a_0
  - r-digest=0.6.29=r41h03ef668_0
  - r-doparallel=1.0.17=r41hc72bb7e_0
  - r-dorng=1.8.2=r41hc72bb7e_1
  - r-dplyr=1.0.7=r41h03ef668_0
  - r-dynamictreecut=1.63_1=r41hc72bb7e_1004
  - r-ellipsis=0.3.2=r41hcfec24a_0
  - r-evaluate=0.15=r41hc72bb7e_0
  - r-fansi=1.0.2=r41hcfec24a_0
  - r-farver=2.1.0=r41h03ef668_0
  - r-fastcluster=1.2.3=r41h9c3ff4c_0
  - r-fastmap=1.1.0=r41h03ef668_0
  - r-fit.models=0.64=r41hc72bb7e_0
  - r-foreach=1.5.2=r41hc72bb7e_0
  - r-foreign=0.8_82=r41hcfec24a_0
  - r-formula=1.2_4=r41hc72bb7e_0
  - r-gdtools=0.2.4=r41h42e24d8_0
  - r-generics=0.1.2=r41hc72bb7e_0
  - r-ggplot2=3.3.5=r41hc72bb7e_0
  - r-glue=1.6.2=r41h06615bd_0
  - r-gridextra=2.3=r41hc72bb7e_1003
  - r-gtable=0.3.0=r41hc72bb7e_3
  - r-highr=0.9=r41hc72bb7e_0
  - r-hmisc=4.6_0=r41h859d828_0
  - r-hms=1.1.1=r41hc72bb7e_0
  - r-htmltable=2.4.0=r41hc72bb7e_0
  - r-htmltools=0.5.2=r41h03ef668_0
  - r-htmlwidgets=1.5.4=r41hc72bb7e_0
  - r-httr=1.4.2=r41hc72bb7e_0
  - r-igraph=1.2.11=r41he0372cf_0
  - r-isoband=0.2.5=r41h03ef668_0
  - r-iterators=1.0.14=r41hc72bb7e_0
  - r-jpeg=0.1_9=r41hcfec24a_0
  - r-jsonlite=1.8.0=r41h06615bd_0
  - r-knitr=1.37=r41hc72bb7e_1
  - r-labeling=0.4.2=r41hc72bb7e_1
  - r-lattice=0.20_45=r41hcfec24a_0
  - r-latticeextra=0.6_29=r41hc72bb7e_1
  - r-lifecycle=1.0.1=r41hc72bb7e_0
  - r-magrittr=2.0.2=r41hcfec24a_0
  - r-mass=7.3_55=r41hcfec24a_0
  - r-matrix=1.4_0=r41he454529_0
  - r-matrixstats=0.61.0=r41hcfec24a_0
  - r-memoise=2.0.1=r41hc72bb7e_0
  - r-mgcv=1.8_39=r41h0154571_0
  - r-mime=0.12=r41hcfec24a_0
  - r-munsell=0.5.0=r41hc72bb7e_1004
  - r-mvtnorm=1.1_3=r41h859d828_0
  - r-nlme=3.1_155=r41h859d828_0
  - r-nnet=7.3_17=r41hcfec24a_0
  - r-openssl=2.0.0=r41hfaab4ff_0
  - r-pcapp=1.9_74=r41h306847c_0
  - r-pillar=1.7.0=r41hc72bb7e_0
  - r-pkgconfig=2.0.3=r41hc72bb7e_1
  - r-pkgload=1.2.4=r41h03ef668_0
  - r-pkgmaker=0.32.2=r41hc72bb7e_0
  - r-plogr=0.2.0=r41hc72bb7e_1003
  - r-png=0.1_7=r41hcfec24a_1004
  - r-praise=1.0.0=r41hc72bb7e_1005
  - r-prettyunits=1.1.1=r41hc72bb7e_1
  - r-processx=3.5.2=r41hcfec24a_0
  - r-progress=1.2.2=r41hc72bb7e_2
  - r-ps=1.6.0=r41hcfec24a_0
  - r-purrr=0.3.4=r41hcfec24a_1
  - r-r6=2.5.1=r41hc72bb7e_0
  - r-rcolorbrewer=1.1_2=r41h785f33e_1003
  - r-rcpp=1.0.8=r41h03ef668_0
  - r-rcurl=1.98_1.6=r41hcfec24a_0
  - r-readr=2.1.2=r41h03ef668_0
  - r-registry=0.5_1=r41hc72bb7e_2
  - r-rematch2=2.1.2=r41hc72bb7e_1
  - r-rlang=0.4.12=r41hcfec24a_0
  - r-rngtools=1.5.2=r41hc72bb7e_0
  - r-robust=0.7_0=r41h52d45c5_0
  - r-robustbase=0.93_9=r41h52d45c5_0
  - r-rpart=4.1.16=r41hcfec24a_0
  - r-rprojroot=2.0.2=r41hc72bb7e_0
  - r-rrcov=1.6_2=r41h742201e_0
  - r-rsqlite=2.2.8=r41h03ef668_0
  - r-rstudioapi=0.13=r41hc72bb7e_0
  - r-scales=1.1.1=r41hc72bb7e_0
  - r-stringi=1.7.6=r41h337692f_1
  - r-stringr=1.4.0=r41hc72bb7e_2
  - r-survival=3.3_1=r41h06615bd_0
  - r-svglite=2.1.0=r41h03ef668_0
  - r-sys=3.4=r41hcfec24a_0
  - r-systemfonts=1.0.4=r41hef9c87a_0
  - r-testthat=3.1.2=r41h03ef668_0
  - r-tibble=3.1.6=r41hcfec24a_0
  - r-tidyselect=1.1.1=r41hc72bb7e_0
  - r-tzdb=0.2.0=r41h03ef668_0
  - r-utf8=1.2.2=r41hcfec24a_0
  - r-vctrs=0.3.8=r41hcfec24a_1
  - r-viridis=0.6.2=r41hc72bb7e_0
  - r-viridislite=0.4.0=r41hc72bb7e_0
  - r-vroom=1.5.7=r41h03ef668_0
  - r-waldo=0.3.1=r41hc72bb7e_0
  - r-webgestaltr=0.4.4=r41h03ef668_0
  - r-wgcna=1.69=r41hecf12ef_5
  - r-whisker=0.4=r41hc72bb7e_1
  - r-withr=2.5.0=r41hc72bb7e_0
  - r-xfun=0.30=r41h7525677_0
  - r-xtable=1.8_4=r41hc72bb7e_3
  - r-yaml=2.3.5=r41h06615bd_0
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.8=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py38h1561384_0
  - scipy=1.8.0=py38h56a6a73_1
  - sed=4.8=he412f7d_0
  - serializable=0.2.0=py_0
  - setuptools=59.5.0=py38h578d9bd_0
  - shap=0.40.0=py38h43a58ef_1
  - simplejson=3.17.6=py38h497a2fe_0
  - six=1.16.0=pyh6c4a22f_0
  - slicer=0.0.7=pyhd8ed1ab_0
  - sqlite=3.37.0=h9cd32fc_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tbb=2021.5.0=h4bd325d_0
  - tensorboard=2.8.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.0=py38h3e25421_1
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tinytimer=0.0.0=py_0
  - tk=8.6.12=h27826a3_0
  - tktable=2.10=hb7b940f_3
  - toml=0.10.2=pyhd8ed1ab_0
  - torchinfo=1.6.3=pyhd8ed1ab_0
  - torchmetrics=0.7.2=pyhd8ed1ab_0
  - tornado=6.1=py38h497a2fe_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typechecks=0.1.0=py_0
  - typing-extensions=4.1.1=hd8ed1ab_0
  - typing_extensions=4.1.1=pyha770c72_0
  - unicodedata2=14.0.0=py38h497a2fe_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - werkzeug=2.0.3=pyhd8ed1ab_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.13.3=py38h497a2fe_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py38h497a2fe_1
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
prefix: /export/home/albert.leung/anaconda3/envs/XAI
