name: XAI
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.3
  - appdirs=1.4.4
  - argh=0.26.2
  - astroid=2.9.3
  - async-timeout=4.0.2
  - attrs=21.4.0
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bioconductor-annotationdbi=1.56.1
  - bioconductor-biobase=2.54.0
  - bioconductor-biocgenerics=0.40.0
  - bioconductor-biocinstaller=1.26.1
  - bioconductor-biostrings=2.62.0
  - bioconductor-genomeinfodb=1.30.0
  - bioconductor-genomeinfodbdata=1.2.7
  - bioconductor-go.db=3.14.0
  - bioconductor-impute=1.68.0
  - bioconductor-iranges=2.28.0
  - bioconductor-keggrest=1.34.0
  - bioconductor-preprocesscore=1.56.0
  - bioconductor-s4vectors=0.32.3
  - bioconductor-xvector=0.34.0
  - bioconductor-zlibbioc=1.40.0
  - biopython=1.79
  - blas=2.113
  - blas-devel=3.9.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=5.0.0
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - configparser=5.2.0
  - cryptography=36.0.1
  - cudatoolkit=10.1.243
  - curl=7.81.0
  - cycler=0.11.0
  - datacache=1.1.5
  - dataclasses=0.8
  - dbus=1.13.6
  - docker-pycreds=0.4.0
  - expat=2.4.6
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.96
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.29.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - frozenlist=1.3.0
  - fsspec=2022.2.0
  - future=0.18.2
  - gcc_impl_linux-64=9.4.0
  - gcc_linux-64=9.4.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.4.0
  - gfortran_linux-64=9.4.0
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - gmp=6.2.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.6
  - gql=0.1.0
  - graphite2=1.3.13
  - graphql-core=3.2.0
  - grpcio=1.44.0
  - gsl=2.7
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gtfparse=1.2.1
  - gxx_impl_linux-64=9.4.0
  - gxx_linux-64=9.4.0
  - harfbuzz=3.4.0
  - icu=69.1
  - idna=3.3
  - importlib-metadata=4.11.1
  - isort=5.10.1
  - jbig=2.1
  - joblib=1.1.0
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lazy-object-proxy=1.7.1
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=7.81.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-devel_linux-64=9.4.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libllvm13=13.0.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.2
  - libprotobuf=3.19.4
  - libsanitizer=9.4.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=9.4.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libuv=1.43.0
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lightning-bolts=0.5.0
  - llvm-openmp=13.0.1
  - llvmlite=0.38.0
  - lz4-c=1.9.3
  - make=4.3
  - markdown=3.3.6
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mccabe=0.6.1
  - memoized-property=1.0.3
  - mkl=2022.0.1
  - mkl-devel=2022.0.1
  - mkl-include=2022.0.1
  - mock=4.0.3
  - multidict=6.0.2
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mysql-common=8.0.28
  - mysql-libs=8.0.28
  - ncurses=6.3
  - ninja=1.10.2
  - nspr=4.32
  - nss=3.74
  - numba=0.55.1
  - numpy=1.21.5
  - nvidia-ml=7.352.0
  - oauthlib=3.2.0
  - openjpeg=2.4.0
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.1
  - pango=1.48.10
  - pathtools=0.1.2
  - pcre=8.45
  - pcre2=10.37
  - pillow=9.0.1
  - pip=22.0.3
  - pixman=0.40.0
  - platformdirs=2.5.1
  - progressbar33=2.4
  - promise=2.3
  - protobuf=3.19.4
  - psutil=5.9.0
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pyensembl=1.9.4
  - pyjwt=2.3.0
  - pylint=2.12.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.8.1
  - pytorch-lightning=1.5.10
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - qt=5.12.9
  - r-acepack=1.4.1
  - r-apcluster=1.4.9
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.1.2
  - r-base64enc=0.1_3
  - r-bibtex=0.4.2.3
  - r-biocmanager=1.30.16
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.2
  - r-brio=1.1.3
  - r-cachem=1.0.6
  - r-callr=3.7.0
  - r-checkmate=2.0.0
  - r-cli=3.2.0
  - r-clipr=0.8.0
  - r-cluster=2.1.2
  - r-codetools=0.2_18
  - r-colorspace=2.0_3
  - r-cpp11=0.4.2
  - r-crayon=1.5.0
  - r-curl=4.3.2
  - r-data.table=1.14.2
  - r-dbi=1.1.2
  - r-deoptimr=1.0_10
  - r-desc=1.4.0
  - r-diffobj=0.3.5
  - r-digest=0.6.29
  - r-doparallel=1.0.17
  - r-dorng=1.8.2
  - r-dplyr=1.0.7
  - r-dynamictreecut=1.63_1
  - r-ellipsis=0.3.2
  - r-evaluate=0.15
  - r-fansi=1.0.2
  - r-farver=2.1.0
  - r-fastcluster=1.2.3
  - r-fastmap=1.1.0
  - r-fit.models=0.64
  - r-foreach=1.5.2
  - r-foreign=0.8_82
  - r-formula=1.2_4
  - r-gdtools=0.2.4
  - r-generics=0.1.2
  - r-ggplot2=3.3.5
  - r-glue=1.6.2
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-highr=0.9
  - r-hmisc=4.6_0
  - r-hms=1.1.1
  - r-htmltable=2.4.0
  - r-htmltools=0.5.2
  - r-htmlwidgets=1.5.4
  - r-httr=1.4.2
  - r-igraph=1.2.11
  - r-isoband=0.2.5
  - r-iterators=1.0.14
  - r-jpeg=0.1_9
  - r-jsonlite=1.8.0
  - r-knitr=1.37
  - r-labeling=0.4.2
  - r-lattice=0.20_45
  - r-latticeextra=0.6_29
  - r-lifecycle=1.0.1
  - r-magrittr=2.0.2
  - r-mass=7.3_55
  - r-matrix=1.4_0
  - r-matrixstats=0.61.0
  - r-memoise=2.0.1
  - r-mgcv=1.8_39
  - r-mime=0.12
  - r-munsell=0.5.0
  - r-mvtnorm=1.1_3
  - r-nlme=3.1_155
  - r-nnet=7.3_17
  - r-openssl=2.0.0
  - r-pcapp=1.9_74
  - r-pillar=1.7.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.4
  - r-pkgmaker=0.32.2
  - r-plogr=0.2.0
  - r-png=0.1_7
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.5.2
  - r-progress=1.2.2
  - r-ps=1.6.0
  - r-purrr=0.3.4
  - r-r6=2.5.1
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.8
  - r-rcurl=1.98_1.6
  - r-readr=2.1.2
  - r-registry=0.5_1
  - r-rematch2=2.1.2
  - r-rlang=0.4.12
  - r-rngtools=1.5.2
  - r-robust=0.7_0
  - r-robustbase=0.93_9
  - r-rpart=4.1.16
  - r-rprojroot=2.0.2
  - r-rrcov=1.6_2
  - r-rsqlite=2.2.8
  - r-rstudioapi=0.13
  - r-scales=1.1.1
  - r-stringi=1.7.6
  - r-stringr=1.4.0
  - r-survival=3.3_1
  - r-svglite=2.1.0
  - r-sys=3.4
  - r-systemfonts=1.0.4
  - r-testthat=3.1.2
  - r-tibble=3.1.6
  - r-tidyselect=1.1.1
  - r-tzdb=0.2.0
  - r-utf8=1.2.2
  - r-vctrs=0.3.8
  - r-viridis=0.6.2
  - r-viridislite=0.4.0
  - r-vroom=1.5.7
  - r-waldo=0.3.1
  - r-webgestaltr=0.4.4
  - r-wgcna=1.69
  - r-whisker=0.4
  - r-withr=2.5.0
  - r-xfun=0.30
  - r-xtable=1.8_4
  - r-yaml=2.3.5
  - readline=8.1
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - sed=4.8
  - sentry-sdk=1.5.8
  - serializable=0.2.0
  - setuptools=59.5.0
  - shap=0.40.0
  - shortuuid=1.0.8
  - simplejson=3.17.6
  - six=1.16.0
  - slicer=0.0.7
  - smmap=3.0.5
  - sqlite=3.37.0
  - subprocess32=3.5.4
  - sysroot_linux-64=2.12
  - tbb=2021.5.0
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - threadpoolctl=3.1.0
  - tinytimer=0.0.0
  - tk=8.6.12
  - tktable=2.10
  - toml=0.10.2
  - torchinfo=1.6.3
  - torchmetrics=0.7.2
  - tornado=6.1
  - tqdm=4.62.3
  - typechecks=0.1.0
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - wandb=0.12.1
  - watchdog=0.10.4
  - werkzeug=2.0.3
  - wheel=0.37.1
  - wrapt=1.13.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
prefix: /export/home/albert.leung/anaconda3/envs/XAI
